enum TransactionType
{
  DEPOSITO = 'DEPOSITO',
  SAQUE = 'SAQUE',
  ENVIO_TRANSFERENCIA = 'ENVIO_TRANSFERENCIA',
  RECEBIMENTO_TRANSFERENCIA = 'RECEBIMENTO_TRANSFERENCIA',
  TAXA_DE_DEPOSITO = 'TAXA_DE_DEPOSITO',
  TAXA_DE_SAQUE = 'TAXA_DE_SAQUE',
  TAXA_DE_TRANSFERENCIA = 'TAXA_DE_TRANSFERENCIA',
}

export { TransactionType };
